package src.Enum.Ingredient;

public enum Ingredient {
    MISTLETOE, CARROT, SALT, FOUR_LEAF_CLOVER, FAIRLY_FRESH_FISH, ROCK_OIL, HONEY, MEAD, SECRET_INGREDIENT, LOBSTER,
    STRAWBERRY, BEET_JUICE, UNICORN_MILK, IDEFIX_HAIR
}
